title: Mikhail M.Meskhi
url: "michaelmmeskhi.github.io"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/michaelmmeskhi"
footer_text: "Last Updated On 08/28/2018"

sass:
    style: compressed
    sass_dir: _sass
