# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Michael M.Meskhi
tagline:          'Personal Website'
description:      'Software Engineer, Future Googler, Artificial Intelligence Enthusiast, Linux <3'
url:              http://mikhailmmeskhi.me
baseurl:          /

author:
  name:           'Michael M.Meskhi'
  url:            https://www.linkedin.com/in/mikhailmmeskhi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/michaelmmeskhi/michaelmmeskhi.github.io
