# Site
title:              Mikhail M.Meskhi
bio:                Software Engineering student @NorthAmericanU
description:        Studying Aritifical Intelligence - Linux Guru
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpeg'
background:         'assets/img/wallpaper.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://mikhailmmeskhi.me

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  input: 	    GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mikhailmmeskhi

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              michael.m.meskhi@live.com
twitter:            michaelmeskhi
#facebook:          michael.m.meskhi
github:             MichaelMMeskhi
stackoverflow:      5110035/michaelmmeskhi
linkedin:           mikhailmmeskhi
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
